### PR TITLE
[chore] Fix request headers

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR fixes the request headers for requesting MesheryAPI and MesheryCloudAPI by setting the missing `provider-token` and `provider` key in cookies

Screenshot 2024-11-30 at 3 39 01 PM

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by theBeginner86** [comment]
After merging this PR we still need to fix the endpoint for triggering the workflow. Currently its seems bogus as its returning 404. 
I don't remember the endpoint so if any of maintainer can please update the endpoint then we should be good 👍

**Comment by theBeginner86** [comment]
Updates:

1. Added support to trigger snapshot workflow in meshery/helm-kanvas-snapshot
2. Added missing kanvas snapshot workflow
3. Removed required email field

This is how it would work: 
Screenshot 2024-12-15 at 4 43 26 PM

**Comment by theBeginner86** [comment]
@leecalcote @jerensl

Though the snapshot service it self is failing for past 2 days, once its fixed then we should be good.
https://github.com/meshery/meshery/actions/workflows/kanvas.yml
https://github.com/meshery/meshery.io/actions/workflows/kanvas.yml

**Comment by theBeginner86** [comment]
Can someone with privileges add the missing GitHub access token that can trigger workflow? It would fix the failing check. Then we can merge and release

https://github.com/meshery/helm-kanvas-snapshot/actions/runs/12338342779/job/34433184955?pr=71

**Review by jerensl — APPROVED** [review]

**Comment by jerensl** [comment]
> Can someone with privileges add the missing GitHub access token that can trigger workflow? It would fix the failing check. Then we can merge and release
> 
> https://github.com/meshery/helm-kanvas-snapshot/actions/runs/12338342779/job/34433184955?pr=71

`GH_ACCESS_TOKEN` is already being set as repository secret

**Review by Aijeyomah — APPROVED** [review]

**Comment by Aijeyomah** [comment]
@theBeginner86 Is this a temporary fix for the unmerged PR in the meshery cloud that already handles triggering of the workflow?

**Review by marblom007 — APPROVED** [review]

**Pull request merged**
