### PR TITLE
Fix issues with helm plugin.

### PR DESCRIPTION
**Pull request by MUzairS15**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Aijeyomah — APPROVED** [review]
Pull the latest change

**Review by hamza-mohd — APPROVED** [review]

**Comment by leecalcote** [comment]
@Aijeyomah, will you assist in eliminating these merge conflicts?

**Comment by leecalcote** [comment]
@Aijeyomah merge conflicts...

**Comment by Aijeyomah** [comment]
> @Aijeyomah merge conflicts...

Resolved

**Comment by leecalcote** [comment]
> @Aijeyomah we'll need for the MeshKit error utility to properly run.

@Aijeyomah we'll need this completed prior to merge.

**Pull request merged**
